rest:
  ssl: false
  host: localhost
  port: 8080
  nameSpace: /server

#  Default Language in which the UI will be rendered if the user's browser language is not an active language
defaultLanguage: pt-BR

# Languages. DSpace Angular holds a message catalog for each of the following languages.
# When set to active, users will be able to switch to the use of this language in the user interface.
languages:
  - code: pt-BR
    label: Português do Brasil
    active: true
  - code: en
    label: English
    active: true
  - code: es
    label: Español
    active: true
  - code: fr
    label: Français
    active: true
